FROM python:3.10 as backend

ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY lib_catalog /app 

RUN pip install --upgrade pip && pip install -r requirements.txt

HEALTHCHECK --interval=5s --timeout=5s --retries=3 CMD ["wget","-nv","-t1","--spider","http://localhost:8000/admin"]

EXPOSE 8000

CMD gunicorn -b 8000:8100 django.wsgi