#From https://github.com/docker-library/postgres/blob/edce9867844e2747021fd77bf3b0e3da560b23c7/14/alpine/Dockerfile

FROM postgres:14-alpine

HEALTHCHECK --interval=10s --timeout=3s CMD /usr/local/bin/pg_isready --username=django || exit 1