version: '3.1'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.front
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - front-backend-network
  database:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes: 
      - $HOME/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: django 
    networks:
      - backend-network

  backend:
    context: .
      dockerfile: Dockerfile.back
    restart: always
    ports:
      - 8000:8000
    networks:
      - front-backend-network
      - backend-network
    depends_on:
      - database       