version: '3.1'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.front
    restart: unless-stopped
    ports:
      - 80:3000    
  database:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes: 
      - $HOME/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: django         

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back  
    command: bash -c "python manage.py migrate && python manage.py loaddata bbk_data && python manage.py runserver 0.0.0.0:8000 "            
    restart: always
    ports:
      - 8000:3000
    depends_on:
      - database   